### ISSUE TITLE
pyyaml not installed with package installation

### ISSUE THREAD

**Issue by annabarone** [cdot65/scm-config-clone#14]
# Summary

After initially creating a virtual environment using Python 3.10 and installing scm-config-clone using pip, the `scm-clone settings` command fails due to a **ModuleNotFoundError: No module named 'yaml'.**

# Steps to Reproduce

1. Create a brand new python environment with `python3 -m venv venv`
2. Activate the environment `source venv/bin/activate`
3. Install the package with `pip install scm-config-clone`
4. Try to run the settings command with `scm-clone settings`

# Error Logs

```shell
abarone@##### scm-config-clone % source .venv/bin/activate
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % python3 --version
Python 3.10.11
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % pip install scm-config-clone
Looking in indexes: https://pypi.org/simple, https://pip_user:****@gitlab.com/api/v4/groups/7692671/-/packages/pypi/simple
Collecting scm-config-clone
  Obtaining dependency information for scm-config-clone from https://files.pythonhosted.org/packages/83/ad/4b47f4c526fcb97c3695f855ff4cf9b928b637fc347a8390fa9bf6a0e17f/scm_config_clone-0.2.1-py3-none-any.whl.metadata
  Using cached scm_config_clone-0.2.1-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: dynaconf<4.0.0,>=3.2.6 in ./.venv/lib/python3.10/site-packages (from scm-config-clone) (3.2.6)
Requirement already satisfied: pan-scm-sdk<0.4.0,>=0.3.4 in ./.venv/lib/python3.10/site-packages (from scm-config-clone) (0.3.6)
Requirement already satisfied: pandas<3.0.0,>=2.2.3 in ./.venv/lib/python3.10/site-packages (from scm-config-clone) (2.2.3)
Requirement already satisfied: setuptools<76.0.0,>=75.1.0 in ./.venv/lib/python3.10/site-packages (from scm-config-clone) (75.6.0)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in ./.venv/lib/python3.10/site-packages (from scm-config-clone) (0.9.0)
Requirement already satisfied: typer<0.13.0,>=0.12.5 in ./.venv/lib/python3.10/site-packages (from scm-config-clone) (0.12.5)
Requirement already satisfied: cryptography<38.0.0,>=37.0.4 in ./.venv/lib/python3.10/site-packages (from pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (37.0.4)
Requirement already satisfied: oauthlib<4.0.0,>=3.2.2 in ./.venv/lib/python3.10/site-packages (from pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (3.2.2)
Requirement already satisfied: pydantic<3.0.0,>=2.9.2 in ./.venv/lib/python3.10/site-packages (from pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.10.3)
Requirement already satisfied: pyjwt<3.0.0,>=2.9.0 in ./.venv/lib/python3.10/site-packages (from pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.10.1)
Requirement already satisfied: requests-oauthlib<3.0.0,>=2.0.0 in ./.venv/lib/python3.10/site-packages (from pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.0.0)
Requirement already satisfied: numpy>=1.22.4 in ./.venv/lib/python3.10/site-packages (from pandas<3.0.0,>=2.2.3->scm-config-clone) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.10/site-packages (from pandas<3.0.0,>=2.2.3->scm-config-clone) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.10/site-packages (from pandas<3.0.0,>=2.2.3->scm-config-clone) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.10/site-packages (from pandas<3.0.0,>=2.2.3->scm-config-clone) (2024.2)
Requirement already satisfied: click>=8.0.0 in ./.venv/lib/python3.10/site-packages (from typer<0.13.0,>=0.12.5->scm-config-clone) (8.1.7)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./.venv/lib/python3.10/site-packages (from typer<0.13.0,>=0.12.5->scm-config-clone) (4.12.2)
Requirement already satisfied: shellingham>=1.3.0 in ./.venv/lib/python3.10/site-packages (from typer<0.13.0,>=0.12.5->scm-config-clone) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in ./.venv/lib/python3.10/site-packages (from typer<0.13.0,>=0.12.5->scm-config-clone) (13.9.4)
Requirement already satisfied: cffi>=1.12 in ./.venv/lib/python3.10/site-packages (from cryptography<38.0.0,>=37.0.4->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (1.17.1)
Requirement already satisfied: annotated-types>=0.6.0 in ./.venv/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.9.2->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.1 in ./.venv/lib/python3.10/site-packages (from pydantic<3.0.0,>=2.9.2->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.27.1)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.2.3->scm-config-clone) (1.17.0)
Requirement already satisfied: requests>=2.0.0 in ./.venv/lib/python3.10/site-packages (from requests-oauthlib<3.0.0,>=2.0.0->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.32.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<0.13.0,>=0.12.5->scm-config-clone) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in ./.venv/lib/python3.10/site-packages (from rich>=10.11.0->typer<0.13.0,>=0.12.5->scm-config-clone) (2.18.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.10/site-packages (from cffi>=1.12->cryptography<38.0.0,>=37.0.4->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.22)
Requirement already satisfied: mdurl~=0.1 in ./.venv/lib/python3.10/site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<0.13.0,>=0.12.5->scm-config-clone) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.venv/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib<3.0.0,>=2.0.0->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in ./.venv/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib<3.0.0,>=2.0.0->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib<3.0.0,>=2.0.0->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in ./.venv/lib/python3.10/site-packages (from requests>=2.0.0->requests-oauthlib<3.0.0,>=2.0.0->pan-scm-sdk<0.4.0,>=0.3.4->scm-config-clone) (2024.12.14)
Using cached scm_config_clone-0.2.1-py3-none-any.whl (75 kB)
Installing collected packages: scm-config-clone
Successfully installed scm-config-clone-0.2.1

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % 
(.venv) abarone@##### scm-config-clone % scm-clone settings
Traceback (most recent call last):
  File "/Users/abarone/code/scm-config-clone/.venv/bin/scm-clone", line 5, in <module>
    from scm_config_clone.main import app
  File "/Users/abarone/code/scm-config-clone/.venv/lib/python3.10/site-packages/scm_config_clone/__init__.py", line 3, in <module>
    from .commands.objects.address import addresses
  File "/Users/abarone/code/scm-config-clone/.venv/lib/python3.10/site-packages/scm_config_clone/commands/objects/address.py", line 19, in <module>
    from scm_config_clone.utilities import load_settings, parse_csv_option
  File "/Users/abarone/code/scm-config-clone/.venv/lib/python3.10/site-packages/scm_config_clone/utilities/__init__.py", line 4, in <module>
    from .settings import load_settings
  File "/Users/abarone/code/scm-config-clone/.venv/lib/python3.10/site-packages/scm_config_clone/utilities/settings.py", line 7, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Comment by cdot65** [comment]
great find, this happened because I recently removed `Dynaconf` from the dependencies and rely now on just loading the settings.yaml file directly with pyyaml, but it looks like we need to update the dependencies.

**Comment by cdot65** [comment]
version 0.2.2. has been uploaded to pypi to account for the missing dependency, thanks for catching this!
